<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="12" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="appiumTestDemo2" duration-ms="11" started-at="2017-10-25T02:36:49Z" finished-at="2017-10-25T02:36:49Z">
    <groups>
    </groups>
    <test name="28a38e6f" duration-ms="11" started-at="2017-10-25T02:36:49Z" finished-at="2017-10-25T02:36:49Z">
      <class name="com.cpeoc.appiunTestDemo.test.yy.MyFirstTest">
        <test-method status="PASS" signature="test001()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.MyFirstTest@604ed9f0]" name="test001" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001 -->
        <test-method status="PASS" signature="test002()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.MyFirstTest@604ed9f0]" name="test002" duration-ms="1" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002 -->
        <test-method status="PASS" signature="test003()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.MyFirstTest@604ed9f0]" name="test003" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test003 -->
      </class> <!-- com.cpeoc.appiunTestDemo.test.yy.MyFirstTest -->
      <class name="com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest">
        <test-method status="PASS" signature="test004()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest@6a4f787b]" name="test004" duration-ms="2" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test004 -->
        <test-method status="PASS" signature="test005()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest@6a4f787b]" name="test005" duration-ms="2" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test005 -->
        <test-method status="FAIL" signature="test006()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest@6a4f787b]" name="test006" duration-ms="2" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest.test006(CopyOfMyFirstTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test006 -->
      </class> <!-- com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest -->
    </test> <!-- 28a38e6f -->
    <test name="127.0.0.1:62001" duration-ms="11" started-at="2017-10-25T02:36:49Z" finished-at="2017-10-25T02:36:49Z">
      <class name="com.cpeoc.appiunTestDemo.test.yy.MyFirstTest">
        <test-method status="PASS" signature="test001()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.MyFirstTest@66a3ffec]" name="test001" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001 -->
        <test-method status="PASS" signature="test002()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.MyFirstTest@66a3ffec]" name="test002" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002 -->
        <test-method status="PASS" signature="test003()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.MyFirstTest@66a3ffec]" name="test003" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test003 -->
      </class> <!-- com.cpeoc.appiunTestDemo.test.yy.MyFirstTest -->
      <class name="com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest">
        <test-method status="PASS" signature="test004()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest@77caeb3e]" name="test004" duration-ms="3" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test004 -->
        <test-method status="PASS" signature="test005()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest@77caeb3e]" name="test005" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test005 -->
        <test-method status="FAIL" signature="test006()[pri:0, instance:com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest@77caeb3e]" name="test006" duration-ms="0" started-at="2017-10-25T10:36:49Z" finished-at="2017-10-25T10:36:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest.test006(CopyOfMyFirstTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test006 -->
      </class> <!-- com.cpeoc.appiunTestDemo.test.yy.CopyOfMyFirstTest -->
    </test> <!-- 127.0.0.1:62001 -->
  </suite> <!-- appiumTestDemo2 -->
</testng-results>
